### ISSUE TITLE
Error while installing : Read-only file system

### ISSUE THREAD

**Issue by nicomeza** [thisiscam/math-with-slack#11]
Hello,

I tried to instll using the command :

> sudo python math-with-slack.py -a /snap/slack/33/usr/lib/slack/resources/app.asar

And I got :

>Using Slack installation at: /snap/slack/33/usr/lib/slack/resources/app.asar
>[Errno 30] Read-only file system: '/snap/slack/33/usr/lib/slack/resources/app.asar.mwsbak'
> Cannot make backup. Make sure the script has write permissions.

I appreciate any suggestion. 

Thanks

**Comment by thisiscam** [comment]
This is the same issue as #9. 
Basically this repo does not support snap install. If you really have to, you might find some of my suggestions in the above issue helpful.
