### ISSUE TITLE
Fails to install: OSError

### ISSUE THREAD

**Issue by cub525** [thisiscam/math-with-slack#12]
![issue](https://user-images.githubusercontent.com/49500036/101218830-0172b180-3641-11eb-9ea3-267a89d0b4e9.png)
I'm using Anaconda and windows 10

**Comment by thisiscam** [comment]
Just for my understanding: which shell and Python are you using? For example, is it batch, power shell or windows bash?

I think I have seen this error occasionally in the CI but was not able to reproduce it. It will be best if you can provide more information so that I can reproduce this.

Thanks!

**Comment by cub525** [comment]
The picture is from windows CMD, I did try it in Powershell as well, although it did fail.
N.B. These are launched through conda 4.9.2 (python isn't in the PATH)

**Comment by thisiscam** [comment]
Ok @cub525 did you make sure that you have Slack closed when running the command? Windows does not allow concurrent file access.

**Comment by thisiscam** [comment]
I added some diagnosis handling for the error reporting. 
Please let me know if the problem persists.

**Comment by cub525** [comment]
Ok, this was all User error, just needed to close slack
