### ISSUE TITLE
Not working (the executable is replaced to switch between architectures for M1 chip?)

### ISSUE THREAD

**Issue by akira-t** [thisiscam/math-with-slack#17]
Not working. (Mac 2020 late Intel, Mac OS 10.15.7, Slack 4.12)
Maybe it is because the binary file "/Applications/Slack.app/Contents/Resources/app.asar" is replaced to switch between the one for Intel chip and M1 chip executables. Once I replace "/Applications/Slack.app/Contents/Resources/app.asar" by "/Applications/Slack.app/Contents/Resources/app-x64.asar", it worked.

---Log---

Using Slack installation at: /Applications/Slack.app/Contents/Resources/app.asar
Traceback (most recent call last):
  File "math-with-slack.py", line 423, in <module>
    ori_injected_file_size = json_header['files']['dist']['files'][injected_file_name]['size']
KeyError: 'dist'

**Comment by thisiscam** [comment]
Thanks for the report. 

Should be fixed by #8c27865 now. Will reopen if there's more problem on arm64 (I don't have an ARM machine at hand to test it).
