### ISSUE TITLE
Installation fails with Errno 22: invalid argument

### ISSUE THREAD

**Issue by galwiner** [thisiscam/math-with-slack#18]
Hi, 
I've tried using both the binary and python script installers but am getting an error. 
I have python 3.7.9 installed, running on win10 64 bit. 
see image below. 
thanks for your help!

Gal 

![image](https://user-images.githubusercontent.com/552959/103652103-4608aa00-4f6b-11eb-9d66-435710aa2e29.png)

**Comment by thisiscam** [comment]
Did you make sure that Slack is closed when running this?

If so, can you check the file permission for the app.asar? 
Most likely you need to run the command as admin. Also see the caveat here https://github.com/thisiscam/math-with-slack#package-and-software-managers

Please let me know if this still doesn't work for you. I have seen this kind of behavior in the CI, but it goes away after I killed the running Slack.

**Comment by galwiner** [comment]
yes, you are right! i just didn't kill it before... silly
thanks very much! works beautifully
