### ISSUE TITLE
Doesn't work on MacOS Big Sur version 11.2.3?

### ISSUE THREAD

**Issue by pranavm1502** [thisiscam/math-with-slack#23]
Hello,

Running the python script appropriately finds a Slack installation and installs mathjax. However, after restarting Slack the latex options don't seem to work. Any ideas?

**Comment by thisiscam** [comment]
I probably need more information. I'm currently on 11.4 and the plugin appears to work fine.
Did you install from App Store or the dmg downloaded from Slack website)? 
What chip is your machine: M1 or intel?
Could you also make sure you only have one copy of Slack installed?

**Comment by thisiscam** [comment]
@pranavm1502 Did you make any progress on this? 
I'm closing this for now, but please reopen if you see any more problems.
