### ISSUE TITLE
Install mathjax from local file

### ISSUE THREAD

**Issue by melsophos** [thisiscam/math-with-slack#26]
It would be useful that `--mathjax-url` could accept also a local path to avoid downloading mathjax. The reason is that when having a snap version of Slack, it is [necessary to reinject mathjax after every reboot](https://github.com/fsavje/math-with-slack/issues/32#issuecomment-479852799).

**Comment by thisiscam** [comment]
I updated the script to address your request.

Let me know if it works for you? The local path needs to point to the `tgz` file you download from [registry.npmjs.org](registry.npmjs.org)

**Comment by melsophos** [comment]
It works well, thanks a lot!
