### ISSUE TITLE
Slack v4.22.0 doesn't open after `math-with-slack` installation

### ISSUE THREAD

**Issue by motiwari** [thisiscam/math-with-slack#27]
`math-with-slack` has stopped working with v4.22.0 and no longer renders LaTeX properly.

I tried reinstalling `math-with-slack` but after doing so, Slack will fail to open and needs to be re-installed.

On MacOS Big Sur 11.6

Repro steps:
- Install Slack v4.22.0 from Mac
- clone the `math-with-slack` repository
- `python math-with-slack.py`
- Try to launch the Slack app

**Comment by thisiscam** [comment]
Oops. 
They updated some things related to security: https://slack.com/release-notes/mac.

I haven't fully consumed what they actually did. But there's a chance that this script will no longer work due to the increased security.

Any help is welcomed!

**Comment by motiwari** [comment]
Thanks for the prompt response; would love to help but unfortunately won't have the time. I'll downgrade to 4.21 for now

**Comment by thisiscam** [comment]
I have a working solution with my manual modifications. I will try to automate this process and report back.

FWIW, reference to the key change:
https://paper.dropbox.com/doc/Electron-ASAR-Integrity-QrEbSA149226qARwYOcp9

**Comment by motiwari** [comment]
Thank you @thisiscam ! For anyone needing a temporary workaround on Mac, I downloaded [Slack v4.21.1](https://slack.en.uptodown.com/mac/download/4052850) , then ran:

`defaults write com.tinyspeck.slackmacgap SlackNoAutoUpdates -bool YES` 
`python math-with-slack.py`

and restarted Slack. Warning: this made me log in to all my workspace again

**Comment by thisiscam** [comment]
@motiwari #29 should address this problem. 

I am willing to know if it works for anyone (or not).

**Comment by motiwari** [comment]
It works now, thank you @thisiscam !

**Comment by motiwari** [comment]
There seems to be another issue now :( -- whenever quitting the Slack app and reopening, it logs the user out of all Slack workspaces and the user needs to log back in to all of them again

**Comment by thisiscam** [comment]
@motiwari Thanks for the find. Let's move the discuss to #30.
