### ISSUE TITLE
SyntaxError line 385 

### ISSUE THREAD

**Issue by dylwil3** [thisiscam/math-with-slack#4]
I'm bad at technology, so here's everything I did (in case I did something obviously silly):

I have MacOS. I copied and pasted everything from the python file (https://raw.githubusercontent.com/thisiscam/math-with-slack/master/math-with-slack.py) into a text document (in Visual Studio Code), saved it as math-with-slack.py in documents, opened terminal, cd to documents, entered "sudo python math-with-slack.py", and then got "SyntaxError line 385" with a little ^ pointing to the e in the line saying "nonlocal start_time". 

Presumably there is not really a syntax error, and I've done something wrong? I tried a couple more times creating a new file and copying and pasting in case I somehow did that wrong... but no dice.

**Comment by thisiscam** [comment]
Nice catch, this is a bug! Thanks for reporting.

I have updated the script, can you try your steps again and see if it works for you?

**Comment by dylwil3** [comment]
It works now! Thank you!
