### ISSUE TITLE
Working in conjunction with code formatting?

### ISSUE THREAD

**Issue by motiwari** [thisiscam/math-with-slack#41]
Thanks for making this extension. Are there any plans for making this work with concurrently with code-formatting in slack?

For example, if I want to type a mathematical algorithm as pseudocode, I may need something like

```
$X$ = 5
```
perhaps this is as simple as checking inside backtick or triple-backtick blocks for latex delimiters and applying the latex style that is congruent with the code formatting?

**Comment by thisiscam** [comment]
You are welcomed to try the above branch and give any feedback!

**Comment by motiwari** [comment]
Thanks for the quick turnaround!

It looks like it works in triple-backtick code blocks:

<img width="218" alt="image" src="https://user-images.githubusercontent.com/13426340/167310864-835dae53-4b25-4b96-bffc-ba918d2f2a96.png">

But not in inline code segments (tried both \` outside of $ and $ outside of \`): 

<img width="105" alt="image" src="https://user-images.githubusercontent.com/13426340/167310887-3518c1ff-b3dc-47b8-9a49-72c5ede624b0.png">

Also, for some reason I had to run the script twice (got a `Missing backup` error), unsure if related:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/13426340/167310934-2d5784e5-4b7b-44be-9c32-6689b177489f.png">

**Comment by thisiscam** [comment]
Just pushed a commit that also enables it for inline code block.

That missing backup is likely something else. It's simply a check there to ensure the plugin did not corrupt Slack.  You should open an issue if this occurs again!

**Comment by motiwari** [comment]
It works!! Incredible!

![image](https://user-images.githubusercontent.com/13426340/167315384-17698265-982c-4fed-b6aa-9d16ac1d9bb7.png)

**Comment by thisiscam** [comment]
I suspect there could be places that this might overshoot, but so far I have not found any. 
I will leave this open for a couple more days for feedbacks.
