### ISSUE TITLE
Installation successful but not working

### ISSUE THREAD

**Issue by JoeyAndBlueWhale** [thisiscam/math-with-slack#44]
The installation was successful. I fully quited slack and restarted it but it is not working. Is it because my slack version is too new? I saw warnings like:
`/Users/dolphinerjoey/Desktop/math-with-slack.py:758: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  return LooseVersion(json.load(f)["version"])
/Users/dolphinerjoey/Desktop/math-with-slack.py:737: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if get_platform() == "darwin" and slack_version >= LooseVersion("4.22"):
/Users/dolphinerjoey/Desktop/math-with-slack.py:763: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if slack_version <= LooseVersion('4.4'):
Downloading MathJax...100%, 4.5 MB / 4.5 MB, 11242.5 KB/s, 0.4 sec
/Users/dolphinerjoey/Desktop/math-with-slack.py:1104: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if platform == "darwin" and slack_version >= LooseVersion("4.22"):`

**Comment by thisiscam** [comment]
I just tried the latest Slack version 4.26.1 and it is working for me.
The warning you see seems to be Python version related. What's your python version?

That said, I would doubt if the warning is related to the functionality of plugin. 

Could you post your macOS version and CPU platform?

**Comment by thisiscam** [comment]
Also, if you just got a new slack install, you need to open Slack at least once, quit slack, then use the plugin. Hope this helps

**Comment by JoeyAndBlueWhale** [comment]
Operating system is Monterey 12.4 and CPU is M1 Max. I completely quited and restarted slack multiple times.

**Comment by thisiscam** [comment]
Hmm, I have 12.3 and and Intel CPU. So your problem could literally be anywhere from CPU platform, script issue to code signing.. 

If you are willing to debug this with me, you can try [these instructions](https://github.com/thisiscam/math-with-slack/issues/40#issuecomment-1088454450), and let me know of your results?

**Comment by JoeyAndBlueWhale** [comment]
There is one issue
<img width="556" alt="issue" src="https://user-images.githubusercontent.com/24945663/172554009-61a3d507-180a-43f9-927c-f9124e1c60c3.png">
and some warnings
<img width="553" alt="warnings" src="https://user-images.githubusercontent.com/24945663/172554058-8fe0daf1-e370-44b6-8f92-7e32cbbc3ef6.png">
