### ISSUE TITLE
Enable texing in pinned posts

### ISSUE THREAD

**Issue by motiwari** [thisiscam/math-with-slack#46]
Pinned posts currently do not currently render in LaTeX:

<img width="485" alt="image" src="https://user-images.githubusercontent.com/13426340/173124623-f48d8243-1cc8-4565-b135-029e64506a82.png">

Is it possible to fix this?

By the way, I realize that you're working on this pro bono as a service to the community. I greatly appreciate your work and hope you don't mind me submitting these feature requests!

**Comment by thisiscam** [comment]
> I greatly appreciate your work and hope you don't mind me submitting these feature requests!

I work on this as a hobby :P 
For the most features, I will implement it as long as I know how and if I have the time
