### ISSUE TITLE
Enable texing in image preview

### ISSUE THREAD

**Issue by motiwari** [thisiscam/math-with-slack#48]
It seems that when you click an image with a description in Slack, it opens a new context. In that context, the LaTeX does not render correctly:

![image](https://user-images.githubusercontent.com/13426340/177225432-0f376200-52fb-450e-8374-e82a94d559e5.png)

Possible to fix?

**Comment by thisiscam** [comment]
Hi @motiwari , I can't reproduce this:
<img width="400" alt="Screen Shot 2022-07-04 at 7 52 18 PM" src="https://user-images.githubusercontent.com/7684342/177226325-ec3b53db-534b-4ce5-af63-78dd3fa48bd0.png">


Which Slack version and system?

**Comment by motiwari** [comment]
My apologies, I updated `math-with-slack` and the problem is resolved. Perhaps I needed the fix in #47
