### ISSUE TITLE
Not working with flatpak version of Slack on ubuntu

### ISSUE THREAD

**Issue by Shashankti** [thisiscam/math-with-slack#49]
I tried specifying the directory of installation as well but got the following error.

`Traceback (most recent call last):
  File "/home/shashank/math_slack.py", line 1116, in <module>
    main()
  File "/home/shashank/math_slack.py", line 1066, in main
    _, asar_extracted_dir = extract_asar(tmp_dir, app_path)
  File "/home/shashank/math_slack.py", line 752, in extract_asar
    asar_extractor = AsarExtractor.open(app_path)
  File "/home/shashank/math_slack.py", line 502, in open
    assert header_data_size == 4
AssertionError`

**Comment by thisiscam** [comment]
Is flatpak the same thing as a snap install? #9

**Comment by roshanshariff** [comment]
If it helps, I had success installing Slack in the user Flatpak installation: `flatpak install --user com.slack.Slack`, and then using `math-with-slack.py` on that installation:
```sh
python3 math-with-slack.py -a ~/.local/share/flatpak/app/com.slack.Slack/current/active/files/extra/lib/slack/resources/app.asar
```

You will need to re-run that second step every time Flatpak updates Slack.
