### ISSUE TITLE
Publish on Slack Apps

### ISSUE THREAD

**Issue by Miladiouss** [thisiscam/math-with-slack#5]
Thank you for your great product. Can you please release it on Slack Apps so it could be installed by non-technical people?

**Comment by thisiscam** [comment]
That would be a very luring idea. However this repo currently does not support publishing as a Slack App, because it needs to inject code into the Slack client itself.

**Comment by thisiscam** [comment]
I am willing to create release versions different OSs so that non-tech people can just click and install the plugin (potentially with a GUI too), would that be of interest to you?

**Comment by Miladiouss** [comment]
That is better than nothing, but I think it is about trust. Perhaps you should contact slack and ask them to include those codes in their next release.

**Comment by Miladiouss** [comment]
This would have huge implications and you can convince them your audience is wide. I'm sure people will support you.

**Comment by thisiscam** [comment]
@Miladiouss I agree that there is a trust issue, on top of the "technical barrier" this cmd tool presents.

I did a few searches a while back, and seems like this LaTeX support is never really on Slack's radar, according to the official Twitter. Here are some random samples (among many other official replies):
https://twitter.com/nart_kenobi/status/1022397187748241408
https://twitter.com/SlackHQ/status/468558184152838144

I'm not sure why the decision by Slack. One plausible reason is that they need to have this support on all platforms or none, which includes IOS clients, that presumably don't use JS technology so they cannot use MathJax natively.

**Comment by thisiscam** [comment]
Closing now as nothing to be done here.
