### ISSUE TITLE
Install script fails on latest macOS

### ISSUE THREAD

**Issue by mirams** [thisiscam/math-with-slack#52]
I'm on the new macOS Sonoma 14, and Slack Version 4.34.121. The install script fails with:
```
% sudo python3 math-with-slack.py
Using Slack installation at: /Applications/Slack.app/Contents/Resources/app.asar
/Users/pmzgm/Downloads/math-with-slack.py:760: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  return LooseVersion(json.load(f)["version"])
/Users/pmzgm/Downloads/math-with-slack.py:739: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if get_platform() == "darwin" and slack_version >= LooseVersion("4.22"):
[Errno 1] Operation not permitted: '/Applications/Slack.app/Contents/Resources/app.asar'
Cannot modify /Applications/Slack.app/Contents/Resources/app.asar. Make sure the script has write permissions. Possibile fix:
	Seems like you are using MacOS. Perhaps your Slack is installed through App Store?
	If that's the case, you will need to use `sudo` to give the script enough permissions. Please check README for more details.
```
suggesting a permissions issue, but I am running with sudo. Any advice?

**Comment by thisiscam** [comment]
I have not upgraded yet. Will reproduce shortly this week or next when I get time. Just to make sure, you did't install from Mac AppStore right?

**Comment by Mert-Okyay** [comment]
having the same issue. running M2 mac mini and using the website installation for M1/M2. any updates?

**Comment by thisiscam** [comment]
I just updated to Sonoma. The script appears to still work for me. I have the x86 chip.

```
sudo python math-with-slack.py --macos-codesign
```

Note the `--macos-codesign` flag.

**Comment by thisiscam** [comment]
I searched a bit more, and it seems like some people have similar issues with other softwares:
- https://discussions.apple.com/thread/255187738
- https://nono.ma/operation-not-permitted-macos-sonoma

Perhaps try the methods mentioned in these threads, if `--macos-codesign` option above is not sufficient? 

For the first link, perhaps try
```
sudo chflags nouchg,noschg /Applications/Slack.app/Contents/Resources/app-{your achitecture}.asar
``` 

For the second link, something like this:
```bash
# Change script to executable 
chmod +x math-with-slack.py

# Give enough permission to ./math-with-slack.py so that it can access `/Applications/Slack.app/Contents/Resources/app-{your achitecture}.asar` 
# follow the post in https://nono.ma/operation-not-permitted-macos-sonoma

# run the script
sudo ./math-with-slack.py --macos-codesign
```

**Comment by mirams** [comment]
I ran with `--macos-codesign` and initially had the same problem. Then I found this setting in the Privacy & Security section:
<img width="484" alt="image" src="https://github.com/thisiscam/math-with-slack/assets/858776/83cd34db-92c9-437f-8867-9091968c1703">
and switching that on as well worked, thanks.

**Comment by Mert-Okyay** [comment]
the app management thing worked for me, thanks!!! However, now everytime i quit slack i have to relogin. anyone have this?

**Comment by thisiscam** [comment]
> the app management thing worked for me, thanks!!! However, now everytime i quit slack i have to relogin. anyone have this?

That symptom sounds like you weren't using the codesign option?

**Comment by Mert-Okyay** [comment]
I did use the codesign option.

**Comment by thisiscam** [comment]
> I did use the codesign option.

Hmm. I don't have this issue. Perhaps try reinstalling Slack? Make sure it's opened once before running the script. Once you installed, the next time you open Slack it should prompt for root permission. If it's not doing that, there's likely something failed with code signing

**Comment by Mert-Okyay** [comment]
So you are right, last time it did not ask for anything so I did reinstall and run the script again (opened slack one time before running the script) and now it asks for "slack safe storage" in the keychain, and requires a password for each channel I am in. Super weird...

**Comment by thisiscam** [comment]
> So you are right, last time it did not ask for anything so I did reinstall and run the script again (opened slack one time before running the script) and now it asks for "slack safe storage" in the keychain, and requires a password for each channel I am in. Super weird...

I think you are seeing the intended behavior now. Glad that it worked out!

**Comment by dpo** [comment]
> I ran with `--macos-codesign` and initially had the same problem. Then I found this setting in the Privacy & Security section: <img alt="image" width="484" src="https://private-user-images.githubusercontent.com/858776/277044570-83cd34db-92c9-437f-8867-9091968c1703.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDk1NzA0OTUsIm5iZiI6MTc0OTU3MDE5NSwicGF0aCI6Ii84NTg3NzYvMjc3MDQ0NTcwLTgzY2QzNGRiLTkyYzktNDM3Zi04ODY3LTkwOTE5NjhjMTcwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDYxMFQxNTQzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGU2NTNiYjQzM2Y4YWM3MTMwY2JiNjQwYTA3MzQwYmNlNjM4ODk3MDc4NjFkYmI2YmU5NjYyOTBiOTBiZDBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MNYO1uf-rZ7pGg4wbgHseCHsJAyX64-ZzKe5pdBXhGo"> and switching that on as well worked, thanks.

This is the key step on macOS. Any chance that those instructions be added to the README?
