### ISSUE TITLE
Getting [WinError 32] while running the script with u flag

### ISSUE THREAD

**Issue by Sivaram46** [thisiscam/math-with-slack#6]
I've downloaded and run your script, but it doesn't work for me. So I want to uninstall it by running the script with `u` flag. Then I got an error as
`Using Slack installation at: c:/Users\username\AppData\Local\slack\app-4.9.0\resources\app.asar
[WinError 32] The process cannot access the file because it is being used by another process: 'c:/Users\\sivaram\\AppData\\Local\\slack\\app-4.9.0\\resources\\app.asar'
Cannot remove previously injected code. Make sure the script has write permissions.`
Could you tell me how can I get rid of this error and render LaTex commands in slack? Thank you in advance.
PS: I'm using Windows 10, slack version 4.9.0

**Comment by thisiscam** [comment]
Can you quit Slack and try again? Overall on Windows one need to quit and restart Slack before and after running the script. Also the script might need Admin permission if Slack is installed at a privileged location.

**Comment by thisiscam** [comment]
But please let me know if still doesn't work for you and I will take a look!

**Comment by thisiscam** [comment]
I'm closing this for now. But let please reopen if anything turns up!
