### ISSUE TITLE
Alternative math delimiters or browser plugin

### ISSUE THREAD

**Issue by voland66** [thisiscam/math-with-slack#7]
Hi,
Thanks for a great script. I wonder if it is possible to make it compatible with a "Latex in slack" plugin which exists for firefox and chrome. That plugin uses non-standard math delimiters, $$ and $$$ for inline and display math respectively. As a result the interoperation of your code with that plugin is imperfect whenever members of a slack group use different solutions. 

The browser plugin has another option for math delimiters: '\(' and '\[' for starting math while ending math with '\)' and '\]'. So one could make the two solutions fully interoperable if the parenthesis/bracket version could  be implemented in math-with-slack as an alternative. I tried adding the second method to math-with-slack.py following http://docs.mathjax.org/en/latest/input/tex/delimiters.html and it almost works but the math is always preceded by '\'.

So my question is whether it is possible to implement the alternative math delimiter in a way that works?

**Comment by thisiscam** [comment]
Have you tried https://github.com/thisiscam/math-with-slack#tex-customization?
I imagine you'd want something like:
```shell
python math-with-slack.py --mathjax-tex-options="{\
  inlineMath: [['$$', '$$'], ['\\\(', '\\\\)']], \
  displayMath: [['$$$', $$$'], ['\\\\[', '\\\\]']], \
}"
```

**Comment by thisiscam** [comment]
Sorry, above doesn't work. Try this instead (tested on my end):
```shell
python math-with-slack.py --mathjax-tex-options="{\
  inlineMath: [['\\\(', '\\\\)'],['\$\$', '\$\$']], \
  displayMath: [['\\\\[', '\\\\]'],['\$\$\$','\$\$\$']], \
}"
```

**Comment by voland66** [comment]
I think it works though what I did is to use '\$' for inline math and 
'\$\$' for display math. This way the standard latex delimiters work and 
I can use parenthesis/brackets when there are users who use browser plugin.

Thanks

Yuri
