### ISSUE TITLE
Math does not render for me on Mac OS Slack 4.10.3

### ISSUE THREAD

**Issue by jmshea** [thisiscam/math-with-slack#8]
I see no difference after installing, although the install said it was successful. Any hints on debugging would be appreciated.

**Comment by thisiscam** [comment]
Make sure that you restart Slack after installing? This means that you need to right click -> quit from the macOS dock.

If you've tried and doesn't work, you can do (after quiting Slack)
```shell
SLACK_DEVLEOPER_MENU=1 open /path/to/Slack.app
```

Then, right click anywhere on Slack -> Inspect Elements -> Console -> See if there's any suspicious warnings/errors?

**Comment by thisiscam** [comment]
Also, I use macOS with 4.10.3 and it is working fine at the moment.

**Comment by jmshea** [comment]
Maybe this is the problem?

DevTools failed to load SourceMap: Could not parse content for https://app.slack.com/client/T01ATF8662V/preload.bundle.js.map: Unexpected token < in JSON at position 0

**Comment by thisiscam** [comment]
I don't think so. That error has been there since version 4.1.0 I believe, and I also have it now. 

Can you send a screenshot of what you are trying to render?  

Another possibility is that there's some rendering bug in MathJax, which we have certainly seen before.

**Comment by jmshea** [comment]
I deleted Slack.app, did a fresh install, reran the installation script, and all is well now. Thanks for your help.
